// JavaScript allows you to use try...catch statements to handle errors gracefully.
try {
   
    let result = x + 5;
    
} catch ( error) {
    console.log("Error : ",error.message);
    
}finally{
    console.log("Program finished");

}